[2025-02-04T23:13:57.636+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T23:13:57.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskD scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-04T23:13:57.665+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskD scheduled__2025-02-01T00:00:00+00:00 [queued]>
[2025-02-04T23:13:57.666+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T23:13:57.680+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): taskD> on 2025-02-01 00:00:00+00:00
[2025-02-04T23:13:57.688+0000] {standard_task_runner.py:72} INFO - Started process 98 to run task
[2025-02-04T23:13:57.692+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskD', 'scheduled__2025-02-01T00:00:00+00:00', '--job-id', '259', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmp04hnpy83']
[2025-02-04T23:13:57.694+0000] {standard_task_runner.py:105} INFO - Job 259: Subtask taskD
[2025-02-04T23:13:57.741+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskD scheduled__2025-02-01T00:00:00+00:00 [running]> on host 099894fbbc67
[2025-02-04T23:13:57.842+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskD' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-01T00:00:00+00:00'
[2025-02-04T23:13:57.843+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T23:13:57.854+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-02-04T23:13:57.856+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo TASK D has executed!']
[2025-02-04T23:13:57.865+0000] {subprocess.py:99} INFO - Output:
[2025-02-04T23:13:57.866+0000] {subprocess.py:106} INFO - TASK D has executed!
[2025-02-04T23:13:57.868+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-02-04T23:13:57.892+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T23:13:57.893+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskD, run_id=scheduled__2025-02-01T00:00:00+00:00, execution_date=20250201T000000, start_date=20250204T231357, end_date=20250204T231357
[2025-02-04T23:13:57.945+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-04T23:13:57.960+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T23:13:57.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
