[2025-01-29T16:30:49.645+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T16:30:49.692+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskC scheduled__2025-01-12T00:00:00+00:00 [queued]>
[2025-01-29T16:30:49.723+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskC scheduled__2025-01-12T00:00:00+00:00 [queued]>
[2025-01-29T16:30:49.726+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T16:30:49.759+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): taskC> on 2025-01-12 00:00:00+00:00
[2025-01-29T16:30:49.771+0000] {standard_task_runner.py:72} INFO - Started process 1871 to run task
[2025-01-29T16:30:49.774+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskC', 'scheduled__2025-01-12T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmpdtqhgz3m']
[2025-01-29T16:30:49.780+0000] {standard_task_runner.py:105} INFO - Job 89: Subtask taskC
[2025-01-29T16:30:49.869+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskC scheduled__2025-01-12T00:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T16:30:50.003+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskC' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-12T00:00:00+00:00'
[2025-01-29T16:30:50.007+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T16:30:50.027+0000] {logging_mixin.py:190} INFO - TASK C has been executed!
[2025-01-29T16:30:50.029+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-29T16:30:50.045+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T16:30:50.046+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskC, run_id=scheduled__2025-01-12T00:00:00+00:00, execution_date=20250112T000000, start_date=20250129T163049, end_date=20250129T163050
[2025-01-29T16:30:50.083+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T16:30:50.115+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T16:30:50.122+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
