[2025-01-29T17:13:53.230+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T17:13:53.263+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskA backfill__2024-12-07T00:00:00+00:00 [queued]>
[2025-01-29T17:13:53.314+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskA backfill__2024-12-07T00:00:00+00:00 [queued]>
[2025-01-29T17:13:53.315+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T17:13:53.340+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): taskA> on 2024-12-07 00:00:00+00:00
[2025-01-29T17:13:53.354+0000] {standard_task_runner.py:72} INFO - Started process 2854 to run task
[2025-01-29T17:13:53.360+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskA', 'backfill__2024-12-07T00:00:00+00:00', '--job-id', '178', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmp5__vhqtn']
[2025-01-29T17:13:53.365+0000] {standard_task_runner.py:105} INFO - Job 178: Subtask taskA
[2025-01-29T17:13:53.460+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskA backfill__2024-12-07T00:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T17:13:53.612+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskA' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-12-07T00:00:00+00:00'
[2025-01-29T17:13:53.631+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T17:13:53.652+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-29T17:13:53.653+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo TASK A has executed']
[2025-01-29T17:13:53.671+0000] {subprocess.py:99} INFO - Output:
[2025-01-29T17:13:53.674+0000] {subprocess.py:106} INFO - TASK A has executed
[2025-01-29T17:13:53.676+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-29T17:13:53.722+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T17:13:53.724+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskA, run_id=backfill__2024-12-07T00:00:00+00:00, execution_date=20241207T000000, start_date=20250129T171353, end_date=20250129T171353
[2025-01-29T17:13:53.779+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T17:13:53.818+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-29T17:13:53.823+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
