[2025-01-29T17:14:13.145+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-29T17:14:13.161+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskD backfill__2024-12-29T00:00:00+00:00 [queued]>
[2025-01-29T17:14:13.169+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cron_catchup_backfill.taskD backfill__2024-12-29T00:00:00+00:00 [queued]>
[2025-01-29T17:14:13.171+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-29T17:14:13.182+0000] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): taskD> on 2024-12-29 00:00:00+00:00
[2025-01-29T17:14:13.189+0000] {standard_task_runner.py:72} INFO - Started process 3157 to run task
[2025-01-29T17:14:13.191+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'cron_catchup_backfill', 'taskD', 'backfill__2024-12-29T00:00:00+00:00', '--job-id', '249', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/executing_cron_catchup_backfill.py', '--cfg-path', '/tmp/tmponxq9v1j']
[2025-01-29T17:14:13.193+0000] {standard_task_runner.py:105} INFO - Job 249: Subtask taskD
[2025-01-29T17:14:13.234+0000] {task_command.py:467} INFO - Running <TaskInstance: cron_catchup_backfill.taskD backfill__2024-12-29T00:00:00+00:00 [running]> on host ef9d5dc750d2
[2025-01-29T17:14:13.322+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cron_catchup_backfill' AIRFLOW_CTX_TASK_ID='taskD' AIRFLOW_CTX_EXECUTION_DATE='2024-12-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-12-29T00:00:00+00:00'
[2025-01-29T17:14:13.324+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-29T17:14:13.334+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-29T17:14:13.336+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'echo TASK D has executed!']
[2025-01-29T17:14:13.347+0000] {subprocess.py:99} INFO - Output:
[2025-01-29T17:14:13.348+0000] {subprocess.py:106} INFO - TASK D has executed!
[2025-01-29T17:14:13.349+0000] {subprocess.py:110} INFO - Command exited with return code 0
[2025-01-29T17:14:13.372+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-29T17:14:13.374+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=cron_catchup_backfill, task_id=taskD, run_id=backfill__2024-12-29T00:00:00+00:00, execution_date=20241229T000000, start_date=20250129T171413, end_date=20250129T171413
[2025-01-29T17:14:13.407+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-29T17:14:13.421+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-29T17:14:13.425+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
